[[headers]]
for = "/*"
[headers.values]
access-control-allow-origin = "*" 

[[plugins]]
package = "@netlify/plugin-nextjs"

[[edge_functions]]
function = "edge-random-redirect"
path = "/redirect/random/from/*"

[dev]
targetPort = 3000
edge_functions = "netlify/edge-functions"
functions = "netlify/functions"

[build]
publish = ".next"
edge_functions = "netlify/edge-functions"
functions = "netlify/functions"
