import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "../styles/globals.css";
import { Wrapper } from "@/components/wrapper";
import { RedirectButton } from "@/components/redirect-button";
import { Layer } from "@/components/layer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <main className="flex h-screen">
          <div className="m-auto w-full">
            <Wrapper>
              {children}
              <Layer>
                <RedirectButton />
              </Layer>
            </Wrapper>
          </div>
        </main>
      </body>
    </html>
  );
}
